export const lightTheme = {
  background: 'var(--color-bg-light)',
  cardBackground: 'var(--color-card-light)',
  text: 'var(--color-text-dark)',
  textSecondary: '#6b7280',
  border: 'var(--color-border-light)',
  primary: 'var(--color-primary)',
  primaryHover: 'var(--color-primary-hover)',
  secondary: 'var(--color-secondary)',
  accent: 'var(--color-accent)',
  claude: 'var(--color-claude)',
  user: 'var(--color-user)',
  error: 'var(--color-error)',
  success: 'var(--color-success)',
  warning: 'var(--color-warning)',
  info: 'var(--color-info)',
  messageBgUser: 'rgba(16, 185, 129, 0.1)',
  messageBgClaude: 'rgba(99, 102, 241, 0.1)',
  shadowSmall: 'var(--shadow-sm)',
  shadowMedium: 'var(--shadow-md)',
  shadowLarge: 'var(--shadow-lg)',
  shadowXL: 'var(--shadow-xl)',
  fontSans: 'var(--font-sans)',
  fontMono: 'var(--font-mono)',
};

export const darkTheme = {
  background: 'var(--color-bg-dark)',
  cardBackground: 'var(--color-card-dark)',
  text: 'var(--color-text-light)',
  textSecondary: '#9ca3af',
  border: 'var(--color-border-dark)',
  primary: 'var(--color-primary)',
  primaryHover: 'var(--color-primary-hover)',
  secondary: 'var(--color-secondary)',
  accent: 'var(--color-accent)',
  claude: 'var(--color-claude)',
  user: 'var(--color-user)',
  error: 'var(--color-error)',
  success: 'var(--color-success)',
  warning: 'var(--color-warning)',
  info: 'var(--color-info)',
  messageBgUser: 'rgba(16, 185, 129, 0.15)',
  messageBgClaude: 'rgba(99, 102, 241, 0.15)',
  shadowSmall: 'var(--shadow-sm-dark)',
  shadowMedium: 'var(--shadow-md-dark)',
  shadowLarge: 'var(--shadow-lg-dark)',
  shadowXL: 'none',
  fontSans: 'var(--font-sans)',
  fontMono: 'var(--font-mono)',
}; 